export interface Team {
	'id': number,
	'url': string,
	'name': string,
	'slug': string,
	'description': string,
	'privacy': string,
	'permission': string,
	'members_url': string,
	'repositories_url': string,
	'parent': Team|null,
	'members_count': 3,
	'repos_count': 10,
	'created_at': string,
	'updated_at': string,
	'organization': {
		'login': string,
		'id': number,
		'url': string,
		'repos_url': string,
		'events_url': string,
		'hooks_url': string,
		'issues_url': string,
		'members_url': string,
		'public_members_url': string,
		'avatar_url': string,
		'description': string,
	},
	// Not an official property, but follows naming scheme seen in Organization
	'html_url': string|undefined,
}
